# Assuming you've read your lists into these two variables:
full_list = """
admin@PhysicianSmart.com
Alice.Short@PhysicianSmart.com
Alicia.Perez@PhysicianSmart.com
Alicia.Walsh@PhysicianSmart.com
Alleen.Reed@PhysicianSmart.com
Amanda.Perry@PhysicianSmart.com
AmandaPerry@PhysicianSmart.com
Amber.Richmond@PhysicianSmart.com
Andrea.Mize@PhysicianSmart.com
Angela.Boughner@PhysicianSmart.com
Angela.Weisgarber@PhysicianSmart.com
Angelica.Huggins@PhysicianSmart.com
Anne.Lee@PhysicianSmart.com
April.Thompson@PhysicianSmart.com
April.Walters@PhysicianSmart.com
Arneca.Franklin@PhysicianSmart.com
Becky.Byrns@PhysicianSmart.com
Bonnie.Merritt@PhysicianSmart.com
Carla.Garrett@PhysicianSmart.com
Carrie.Ward@PhysicianSmart.com
Cheyoko.Baumgartner@PhysicianSmart.com
Christie.Luis@PhysicianSmart.com
Christina.McCoy@PhysicianSmart.com
Christina.Urban@PhysicianSmart.com
Cindy.Brown@PhysicianSmart.com
Cindy.Masters@PhysicianSmart.com
Cindy.Wooley@PhysicianSmart.com
Connie.Pinkner@PhysicianSmart.com
Crystal.Guidry@PhysicianSmart.com
Dana.Nicholson@PhysicianSmart.com
Danielle.HovingtonNeville@PhysicianSmart.com
Darci.Robbins@PhysicianSmart.com
David.Lopez@PhysicianSmart.com
Diane.Laucirica@PhysicianSmart.com
Dianne.Kirk@PhysicianSmart.com
Dolores.Mendez@PhysicianSmart.com
Duvane.Hodge@PhysicianSmart.com
Elisabeth.King@PhysicianSmart.com
Elizabeth.Beeton@PhysicianSmart.com
Gay.Farrar@PhysicianSmart.com
HIPAASecure@PhysicianSmart.com
Jamie.Molina@PhysicianSmart.com
Jamie.Tackett@PhysicianSmart.com
Janet.Redden@PhysicianSmart.com
Jeannie.Wagener@PhysicianSmart.com
Jen.Skelton@PhysicianSmart.com
Jessica.Majors@PhysicianSmart.com
Jill.Miller@PhysicianSmart.com
Jill.Taraz@PhysicianSmart.com
Jorgeanne.Baker@PhysicianSmart.com
Kaitlyn.Guidry@PhysicianSmart.com
Karana.Apals@PhysicianSmart.com
Karen.Battistelli@PhysicianSmart.com
Karla.Sanchez@PhysicianSmart.com
KaroleMaxfieldGrimstad@PhysicianSmart.com
Kelli.Prusinski@PhysicianSmart.com
Khadijah.Arshad@PhysicianSmart.com
Kristen.Trexler@PhysicianSmart.com
Kristie.Palmer@PhysicianSmart.com
Kristin.Mulhollen@PhysicianSmart.com
Lakishia.Moncree@PhysicianSmart.com
Laura.Bertke@PhysicianSmart.com
Leslie.Griffis@PhysicianSmart.com
Lia.Walther@PhysicianSmart.com
Linda.Freshour@PhysicianSmart.com
Lisa.Alaniz@PhysicianSmart.com
Lisa.Petrecca@PhysicianSmart.com
Liz.Mathews@PhysicianSmart.com
Lucretia.Sines@PhysicianSmart.com
Lynda.Hammett@PhysicianSmart.com
Maggie.Smith@PhysicianSmart.com
Marian.Meyer@PhysicianSmart.com
Maulik.Bakshi@PhysicianSmart.com
Megan.Shannon@PhysicianSmart.com
Melissa.McCarthy@PhysicianSmart.com
Michelle.Huggins@PhysicianSmart.com
Nakesha.Jackson@PhysicianSmart.com
Nancy.Cameron@PhysicianSmart.com
Nancy.Valle@PhysicianSmart.com
Nicholas.Korneluk@PhysicianSmart.com
Patricia.Henderson@PhysicianSmart.com
psn@physiciansmart.com
Randi.Albers@PhysicianSmart.com
Rhonda.Davidson@PhysicianSmart.com
Robin.Beveridge@PhysicianSmart.com
Robin.Heiney@PhysicianSmart.com
Rochelle.Harmon@PhysicianSmart.com
Sally.Martin@PhysicianSmart.com
Sam.Kaleiwahea@PhysicianSmart.com
Sandra.Stecklein@PhysicianSmart.com
Sarah.Allison@PhysicianSmart.com
Sarah.Caison@PhysicianSmart.com
Saran.Henson@PhysicianSmart.com
Sharon.Marsala@PhysicianSmart.com
Shawnee.Ramirez@PhysicianSmart.com
Stephanie.Gray@PhysicianSmart.com
Stephanie.Woelfel@PhysicianSmart.com
Susan.Eisenberg@PhysicianSmart.com
Tami.O'Daniel@PhysicianSmart.com
Terri.Arterburn@PhysicianSmart.com
TestUser@PhysicianSmart.com
Tina.Bruni@PhysicianSmart.com
Tracy.Kopitsch@PhysicianSmart.com
Vanessa.Edwards@PhysicianSmart.com
""".strip().split('\n')

second_list = """
Alice.Short@PhysicianSmart.com
Alicia.Perez@PhysicianSmart.com
Alicia.Walsh@PhysicianSmart.com
Alleen.Reed@PhysicianSmart.com
amanda.perry@physiciansmart.com
Amber.Richmond@PhysicianSmart.com
Andrea.Mize@PhysicianSmart.com
Angela.Boughner@PhysicianSmart.com
Angela.Weisgarber@PhysicianSmart.com
Angelica.Huggins@PhysicianSmart.com
Anne.Lee@PhysicianSmart.com
April.Thompson@PhysicianSmart.com
April.Walters@PhysicianSmart.com
Arneca.Franklin@PhysicianSmart.com
Becky.Byrns@PhysicianSmart.com
Bonnie.merritt@PhysicianSmart.com
Carla.Garrett@PhysicianSmart.com
Carrie.Ward@PhysicianSmart.com
Cheyoko.Baumgartner@PhysicianSmart.com
Christie.Luis@PhysicianSmart.com
Christina.Urban@PhysicianSmart.com
Cindy.Brown@PhysicianSmart.com
Cindy.Masters@PhysicianSmart.com
Cindy.Wooley@PhysicianSmart.com
Crystal.Guidry@PhysicianSmart.com
Dana.Nicholson@PhysicianSmart.com
Danielle.HovingtonNeville@PhysicianSmart.com
Darci.Robbins@PhysicianSmart.com
Diane.Laucirica@PhysicianSmart.com
Dianne.Kirk@PhysicianSmart.com
Dolores.Mendez@PhysicianSmart.com
Duvane.Hodge@PhysicianSmart.com
Elisabeth.King@PhysicianSmart.com
Elizabeth.Beeton@PhysicianSmart.com
Gay.Farrar@PhysicianSmart.com
Jamie.Molina@PhysicianSmart.com
Janet.Redden@PhysicianSmart.com
Jeannie.Wagener@PhysicianSmart.com
Jen.Skelton@PhysicianSmart.com
Jennifer.Smith@PhysicianSmart.com
Jessica.Majors@PhysicianSmart.com
Jill.Miller@PhysicianSmart.com
Jill.Taraz@PhysicianSmart.com
Jorgeanne.Baker@PhysicianSmart.com
Karana.Apals@PhysicianSmart.com
Karla.Sanchez@PhysicianSmart.com
KaroleMaxfieldGrimstad@PhysicianSmart.com
Kelli.Prusinski@PhysicianSmart.com
Kristie.Palmer@PhysicianSmart.com
Kristin.Mulhollen@PhysicianSmart.com
Laura.Bertke@PhysicianSmart.com
Lia.Walther@PhysicianSmart.com
Linda.Freshour@PhysicianSmart.com
lisa.petrecca@PhysicianSmart.com
Liz.Mathews@PhysicianSmart.com
Lucretia.Sines@PhysicianSmart.com
Lynda.Hammett@PhysicianSmart.com
Marian.Meyer@PhysicianSmart.com
Maulik.Bakshi@PhysicianSmart.com
Megan.Shannon@PhysicianSmart.com
Melissa.McCarthy@PhysicianSmart.com
Mia.Blackwell-Charley@PhysicianSmart.com
Michelle.Huggins@PhysicianSmart.com
Nakesha.Jackson@PhysicianSmart.com
Nancy.Cameron@PhysicianSmart.com
Nancy.Valle@PhysicianSmart.com
Nkorneluk@ICQC.org
Patricia.Henderson@PhysicianSmart.com
Randi.Albers@PhysicianSmart.com
Rhonda.Davidson@PhysicianSmart.com
Robin.Beveridge@PhysicianSmart.com
Robin.Heiney@PhysicianSmart.com
Rochelle.Harmon@PhysicianSmart.com
Sally.Martin@PhysicianSmart.com
Sam.Kaleiwahea@PhysicianSmart.com
Sandra.Stecklein@PhysicianSmart.com
Sarah.Allison@PhysicianSmart.com
Sarah.Caison@PhysicianSmart.com
Saran.Henson@PhysicianSmart.com
Sharon.Marsala@PhysicianSmart.com
Shawnee.Ramirez@PhysicianSmart.com
Stephanie.Gray@PhysicianSmart.com
Stephanie.Woelfel@PhysicianSmart.com
Susan.Eisenberg@PhysicianSmart.com
Tami.O'Daniel@PhysicianSmart.com
Terri.Arterburn@PhysicianSmart.com
Tina.Bruni@PhysicianSmart.com
Tracy.Kopitsch@PhysicianSmart.com
Tricia.Spence@PhysicianSmart.com
Vanessa.Edwards@PhysicianSmart.com

""".strip().split('\n')

# Convert emails to lowercase to ensure case-insensitive comparison
full_list = [email.lower() for email in full_list]
second_list = [email.lower() for email in second_list]

# Find which emails are in the full list but not in the second list
missing_emails = [email for email in full_list if email not in second_list]

# Print the missing emails
print("Emails missing in the second list:")
for x in missing_emails:
    print(x)